objectStorage:
    accessKeyID: '2.11E3UccBsPJ85vEGLm+x/g==.omqMCugKfHGShK+PkCyu0Q==.5gJCsxijZcG3OYp5kC9lYG0yJz0='
    secretAccessKey: '2.mAQFpLouj16vnyLColTXlQ==.3tf5so7A6MpXII3nMtIWhg==.Iy7jlU10VcsYJj4jpDBp5PccoXvFjtkzTs163OmbpXmfGVqjOOlr+A=='
wellknown:
    domain: pawnode-wellknown.s3.amazonaws.com
    path: ''
    bucketName: pawnode-wellknown
crypto:
    minValidDays: 30
    bucketName: pawnode-crypto
siteDir: /var/www/sites
