objectStorage:
    accessKeyID: '2.dt/kp/278UprY71Ysm6gKg==.sznFLuitbCp1Y7o9c06tZQ==.i5U+/LMQIgjC4IYHQtAXumobNiQ='
    secretAccessKey: '2.NEhFLMwjyeGAseTfrhc6uQ==.XjrZ0pWEoUwzpLdAFQa9jg==.lswix4SJpCrPMFpDmI2yxcJ2vdc2A8nJmjjFlrIJY2iRRxsmroIkDA=='
wellknown:
    domain: doridian-cdn-wellknown.s3.amazonaws.com
    path: ''
    bucketName: doridian-cdn-wellknown
crypto:
    minValidDays: 30
    bucketName: doridian-cdn-crypto
siteDir: /var/www/sites
defaultCert: /etc/ssl/default.crt
defaultKey: /etc/ssl/default.key
