name: CD

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run deploy
      env:
        SSH_KEY: ${{ secrets.SSH_KEY }}
      run: |
        set -euo pipefail
        echo "$SSH_KEY" > ssh-keyfile
        chmod 600 ssh-keyfile
        for loc in nyc1 las1 lux1
        do
            n=0
            until [ $n -ge 5 ]
            do
              ssh -oUserKnownHostsFile=./ci/known-hosts -i ssh-keyfile "deployer@$loc.pawnode.com" && break || true
              n=$[$n+1]
              sleep 5
            done
            if [ $n -ge 5 ]
            then
              exit 1
            fi
        done
        rm ssh-keyfile
