name: CD

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Run deploy
      env:
        SSH_KEY: ${{ secrets.SSH_KEY }}
      run: |
        echo "$SSH_KEY" > ssh-keyfile
        ssh -i ssh-keyfile deployer@sea01.pawnode.com
        ssh -i ssh-keyfile deployer@nyc01.pawnode.com
        ssh -i ssh-keyfile deployer@van01.pawnode.com
        ssh -i ssh-keyfile deployer@fra01.pawnode.com
        rm ssh-keyfile
